# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MY.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets
import myXMLOperations as myXML
import firmaXMLOperations as fXML
from PyQt5.QtWidgets import QTableWidgetItem

class Ui_MyForm(object):

    def __init__(self):
        self.myForm = QtWidgets.QWidget()

    def setupUi(self):
        self.myForm.setObjectName("MyForm")
        self.myForm.resize(641, 640)
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.myForm)
        self.horizontalLayout.setContentsMargins(80, 5, 80, 5)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.MyBox = QtWidgets.QGroupBox(self.myForm)
        font = QtGui.QFont()
        font.setFamily("Calibri Light")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.MyBox.setFont(font)
        self.MyBox.setAlignment(QtCore.Qt.AlignCenter)
        self.MyBox.setObjectName("MyBox")
        self.formLayout = QtWidgets.QFormLayout(self.MyBox)
        self.formLayout.setLabelAlignment(QtCore.Qt.AlignCenter)
        self.formLayout.setFormAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.MyBox)
        font = QtGui.QFont()
        font.setFamily("Calibri Light")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.datumTxt = QtWidgets.QLineEdit(self.MyBox)
        self.datumTxt.setMaximumSize(QtCore.QSize(120, 16777215))
        font = QtGui.QFont()
        font.setFamily("Calibri Light")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.datumTxt.setFont(font)
        self.datumTxt.setFrame(False)
        self.datumTxt.setAlignment(QtCore.Qt.AlignCenter)
        self.datumTxt.setReadOnly(True)
        self.datumTxt.setObjectName("datumTxt")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.datumTxt)
        self.label_3 = QtWidgets.QLabel(self.MyBox)
        font = QtGui.QFont()
        font.setFamily("Calibri Light")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.matBrTxt = QtWidgets.QLineEdit(self.MyBox)
        self.matBrTxt.setEnabled(True)
        self.matBrTxt.setMaximumSize(QtCore.QSize(120, 16777215))
        font = QtGui.QFont()
        font.setFamily("Calibri Light")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.matBrTxt.setFont(font)
        self.matBrTxt.setFrame(False)
        self.matBrTxt.setAlignment(QtCore.Qt.AlignCenter)
        self.matBrTxt.setReadOnly(True)
        self.matBrTxt.setObjectName("matBrTxt")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.matBrTxt)
        self.label_2 = QtWidgets.QLabel(self.MyBox)
        font = QtGui.QFont()
        font.setFamily("Calibri Light")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.rbrTxt = QtWidgets.QLineEdit(self.MyBox)
        self.rbrTxt.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setFamily("Calibri Light")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.rbrTxt.setFont(font)
        self.rbrTxt.setFrame(False)
        self.rbrTxt.setAlignment(QtCore.Qt.AlignCenter)
        self.rbrTxt.setReadOnly(True)
        self.rbrTxt.setObjectName("rbrTxt")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.rbrTxt)
        self.label_4 = QtWidgets.QLabel(self.MyBox)
        font = QtGui.QFont()
        font.setFamily("Calibri Light")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.brOizTxt = QtWidgets.QLineEdit(self.MyBox)
        self.brOizTxt.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setFamily("Calibri Light")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.brOizTxt.setFont(font)
        self.brOizTxt.setFrame(False)
        self.brOizTxt.setAlignment(QtCore.Qt.AlignCenter)
        self.brOizTxt.setReadOnly(True)
        self.brOizTxt.setObjectName("brOizTxt")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.brOizTxt)
        self.label_5 = QtWidgets.QLabel(self.MyBox)
        font = QtGui.QFont()
        font.setFamily("Calibri Light")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.podObradioTxt = QtWidgets.QLineEdit(self.MyBox)
        self.podObradioTxt.setMaximumSize(QtCore.QSize(250, 16777215))
        font = QtGui.QFont()
        font.setFamily("Calibri Light")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.podObradioTxt.setFont(font)
        self.podObradioTxt.setAlignment(QtCore.Qt.AlignCenter)
        self.podObradioTxt.setObjectName("podObradioTxt")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.podObradioTxt)
        self.kontaktBox = QtWidgets.QGroupBox(self.MyBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.kontaktBox.sizePolicy().hasHeightForWidth())
        self.kontaktBox.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.kontaktBox.setFont(font)
        self.kontaktBox.setObjectName("kontaktBox")
        self.formLayout_2 = QtWidgets.QFormLayout(self.kontaktBox)
        self.formLayout_2.setLabelAlignment(QtCore.Qt.AlignCenter)
        self.formLayout_2.setFormAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_6 = QtWidgets.QLabel(self.kontaktBox)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.label_7 = QtWidgets.QLabel(self.kontaktBox)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.kontaktTelTxt = QtWidgets.QLineEdit(self.kontaktBox)
        self.kontaktTelTxt.setMaximumSize(QtCore.QSize(175, 16777215))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.kontaktTelTxt.setFont(font)
        self.kontaktTelTxt.setAlignment(QtCore.Qt.AlignCenter)
        self.kontaktTelTxt.setObjectName("kontaktTelTxt")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.kontaktTelTxt)
        self.mailTxt = QtWidgets.QLineEdit(self.kontaktBox)
        self.mailTxt.setMaximumSize(QtCore.QSize(300, 16777215))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.mailTxt.setFont(font)
        self.mailTxt.setAlignment(QtCore.Qt.AlignCenter)
        self.mailTxt.setObjectName("mailTxt")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.mailTxt)
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.SpanningRole, self.kontaktBox)
        self.lokacijeBox = QtWidgets.QGroupBox(self.MyBox)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lokacijeBox.setFont(font)
        self.lokacijeBox.setObjectName("lokacijeBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.lokacijeBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tableWidget = QtWidgets.QTableWidget(self.lokacijeBox)
        font = QtGui.QFont()
        font.setFamily("Calibri Light")
        font.setPointSize(12)
        self.tableWidget.setFont(font)
        self.tableWidget.setFrameShape(QtWidgets.QFrame.Box)
        self.tableWidget.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.tableWidget.setSelectionMode(QtWidgets.QAbstractItemView.NoSelection)
        self.tableWidget.setShowGrid(False)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.verticalLayout.addWidget(self.tableWidget)
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.SpanningRole, self.lokacijeBox)
        self.frame = QtWidgets.QFrame(self.MyBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_2.setSpacing(100)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.nazadBtn = QtWidgets.QPushButton(self.frame)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.nazadBtn.setFont(font)
        self.nazadBtn.setObjectName("nazadBtn")

        self.nazadBtn.clicked.connect(self.nazadBtnClick)

        self.horizontalLayout_2.addWidget(self.nazadBtn)
        self.napraviBtn = QtWidgets.QPushButton(self.frame)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.napraviBtn.setFont(font)
        self.napraviBtn.setObjectName("napraviBtn")
        self.horizontalLayout_2.addWidget(self.napraviBtn)
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.SpanningRole, self.frame)
        self.horizontalLayout.addWidget(self.MyBox)
        self.napraviBtn.clicked.connect(self.sacuvajObrazac)
        self.retranslateUi()
        QtCore.QMetaObject.connectSlotsByName(self.myForm)

        self.datumTxt.setFocusPolicy(QtCore.Qt.NoFocus)
        self.rbrTxt.setFocusPolicy(QtCore.Qt.NoFocus)
        self.brOizTxt.setFocusPolicy(QtCore.Qt.NoFocus)
        self.matBrTxt.setFocusPolicy(QtCore.Qt.NoFocus)

        self.datumTxt.setText(myXML.MyXML.getDatum())
        self.matBrTxt.setText(fXML.getMatBr())
        self.brOizTxt.setText("1")
        self.rbrTxt.setText("1")

    def retranslateUi(self):
        _translate = QtCore.QCoreApplication.translate
        self.myForm.setWindowTitle(_translate("MyForm", "MY Obrazac"))
        self.MyBox.setTitle(_translate("MyForm", "MY Obrazac"))
        self.label.setText(_translate("MyForm", "Datum izveštaja:"))
        self.datumTxt.setPlaceholderText(_translate("MyForm", "dd.mm.gggg"))
        self.label_3.setText(_translate("MyForm", "Matični broj:"))
        self.matBrTxt.setPlaceholderText(_translate("MyForm", "XXXXXXXX"))
        self.label_2.setText(_translate("MyForm", "Redni broj:"))
        self.rbrTxt.setPlaceholderText(_translate("MyForm", "1"))
        self.label_4.setText(_translate("MyForm", "Broj OIZ:"))
        self.brOizTxt.setPlaceholderText(_translate("MyForm", "1"))
        self.label_5.setText(_translate("MyForm", "Podatke obradio:"))
        self.podObradioTxt.setPlaceholderText(_translate("MyForm", "Aleksandra Stanojević"))
        self.kontaktBox.setTitle(_translate("MyForm", "Kontakt"))
        self.label_6.setText(_translate("MyForm", "Kontakt telefon:"))
        self.label_7.setText(_translate("MyForm", "E-mail:"))
        self.kontaktTelTxt.setPlaceholderText(_translate("MyForm", "+381619533214"))
        self.mailTxt.setPlaceholderText(_translate("MyForm", "someone@hotmail.com"))
        self.lokacijeBox.setTitle(_translate("MyForm", "Lokacije"))
        self.nazadBtn.setText(_translate("MyForm", "Nazad"))
        self.napraviBtn.setText(_translate("MyForm", "Sačuvaj obrazac"))
        self.tableWidget.setFocusPolicy(QtCore.Qt.NoFocus)
        self.setTableWidgetProperties()
        self.fillTableWidget()

    def nazadBtnClick(self):
        self.myForm.hide()

    def sacuvajObrazac(self):
        date = self.datumTxt.text()
        matbr = self.matBrTxt.text()
        rbr = self.rbrTxt.text()
        broiz = self.brOizTxt.text()
        kontakt = self.kontaktTelTxt.text() + ";" + self.mailTxt.text()
        kor = self.podObradioTxt.text()
        myXML.MyXML.popuniMYObrazac(date, matbr, rbr, broiz, kor, kontakt)



    def setTableWidgetProperties(self):
        self.tableWidget.setRowCount(len(fXML.Lokacija.sve_lokacije()))
        self.tableWidget.setColumnCount(4)
        self.tableWidget.setUpdatesEnabled(True)
        self.tableWidget.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidget.setColumnWidth(0, 0)
        self.tableWidget.setColumnWidth(1, 100)
        self.tableWidget.setColumnWidth(2, 100)
        self.tableWidget.setColumnWidth(3, 150)

        self.tableWidget.horizontalHeader().setStretchLastSection(True)

        font = QtGui.QFont()
        font.setFamily("Calibri Light")
        font.setPointSize(13)
        font.setBold(True)

        cid = QTableWidgetItem("Id")
        cid.setFont(font)

        cnaziv = QTableWidgetItem("Naziv")
        cnaziv.setFont(font)

        cmesto = QTableWidgetItem("Mesto")
        cmesto.setFont(font)

        cadresa = QTableWidgetItem("Adresa")
        cadresa.setFont(font)

        self.tableWidget.setHorizontalHeaderItem(0, cid)
        self.tableWidget.setHorizontalHeaderItem(1, cnaziv)
        self.tableWidget.setHorizontalHeaderItem(2, cmesto)
        self.tableWidget.setHorizontalHeaderItem(3, cadresa)

    def fillTableWidget(self):
        self.tableWidget.clearContents()
        lokacije = fXML.Lokacija.sve_lokacije()
        font = QtGui.QFont()
        font.setFamily("Calibri Light")
        font.setPointSize(11)
        font.setBold(False)
        for i in range(len(lokacije)):
            naziv = QTableWidgetItem(lokacije[i].naziv)
            naziv.setFont(font)
            mesto = QTableWidgetItem(lokacije[i].mesto)
            mesto.setFont(font)
            adresa = QTableWidgetItem(lokacije[i].adresa)
            adresa.setFont(font)

            self.tableWidget.setItem(i, 0, QTableWidgetItem(lokacije[i].id))
            self.tableWidget.setItem(i, 1, naziv)
            self.tableWidget.setItem(i, 2, mesto)
            self.tableWidget.setItem(i, 3, adresa)

        self.tableWidget.setColumnWidth(0, 0)
        self.tableWidget.hideColumn(0)


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MyForm = QtWidgets.QWidget()
    ui = Ui_MyForm()
    ui.setupUi()
    ui.myForm.show()
    sys.exit(app.exec_())
